// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThaniyasFarmerAppAPI.Repository;

namespace ThaniyasFarmerAppAPI.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20200312032810_Store_Registration")]
    partial class Store_Registration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.Configuration", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("DateModified");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Name");

                    b.Property<int?>("ParentID");

                    b.Property<string>("Text");

                    b.Property<string>("Type");

                    b.Property<string>("Value");

                    b.HasKey("ID");

                    b.ToTable("Configurations");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DateAdded = new DateTime(2020, 3, 12, 3, 28, 10, 368, DateTimeKind.Utc).AddTicks(2611),
                            DateModified = new DateTime(2020, 3, 12, 3, 28, 10, 368, DateTimeKind.Utc).AddTicks(2612),
                            Deleted = false,
                            Name = "UserID",
                            Type = "SystemEmailSettings",
                            Value = "vNp/Rg/59Wq/aUZBS0+1LDWmAArWOdzzJByWFcSqj9c="
                        },
                        new
                        {
                            ID = 2,
                            DateAdded = new DateTime(2020, 3, 12, 3, 28, 10, 368, DateTimeKind.Utc).AddTicks(8010),
                            DateModified = new DateTime(2020, 3, 12, 3, 28, 10, 368, DateTimeKind.Utc).AddTicks(8011),
                            Deleted = false,
                            Name = "Password",
                            Type = "SystemEmailSettings",
                            Value = "DR7VkCQllyJBLRHqnhoFLg=="
                        },
                        new
                        {
                            ID = 3,
                            DateAdded = new DateTime(2020, 3, 12, 3, 28, 10, 368, DateTimeKind.Utc).AddTicks(9487),
                            DateModified = new DateTime(2020, 3, 12, 3, 28, 10, 368, DateTimeKind.Utc).AddTicks(9488),
                            Deleted = false,
                            Name = "SMTPPort",
                            Type = "SystemEmailSettings",
                            Value = "KfPgC+VOAFLCwNmgAKPmfQ=="
                        },
                        new
                        {
                            ID = 4,
                            DateAdded = new DateTime(2020, 3, 12, 3, 28, 10, 369, DateTimeKind.Utc).AddTicks(863),
                            DateModified = new DateTime(2020, 3, 12, 3, 28, 10, 369, DateTimeKind.Utc).AddTicks(864),
                            Deleted = false,
                            Name = "Host",
                            Type = "SystemEmailSettings",
                            Value = "+fNJD/SKxu6Pyz64X9mIMQ=="
                        });
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.Harvestings", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cost")
                        .HasMaxLength(50);

                    b.Property<string>("Date");

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("DateModified");

                    b.Property<bool>("Deleted");

                    b.Property<int>("LabourCost");

                    b.Property<int?>("LandDetailIDFK");

                    b.Property<string>("NOofLabours")
                        .HasMaxLength(50);

                    b.Property<int?>("PartitionLandDetailIDFK");

                    b.HasKey("ID");

                    b.HasIndex("LandDetailIDFK");

                    b.HasIndex("PartitionLandDetailIDFK");

                    b.ToTable("Harvestings");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.LandDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AreaSize");

                    b.Property<string>("City")
                        .HasMaxLength(50);

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("DateModified");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75);

                    b.Property<string>("PattaNumber")
                        .HasMaxLength(50);

                    b.Property<int?>("StateListId");

                    b.Property<string>("Village")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.HasIndex("StateListId");

                    b.ToTable("LandDetails");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.PartitionLandDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AreaSize")
                        .IsRequired()
                        .HasMaxLength(75);

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("DateModified");

                    b.Property<bool>("Deleted");

                    b.Property<int?>("LandDetailId");

                    b.Property<string>("LandDirection")
                        .IsRequired()
                        .HasMaxLength(75);

                    b.HasKey("ID");

                    b.HasIndex("LandDetailId");

                    b.ToTable("PartitionLandDetails");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.PestControl", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cost")
                        .HasMaxLength(50);

                    b.Property<string>("Date");

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("DateModified");

                    b.Property<bool>("Deleted")
                        .HasMaxLength(50);

                    b.Property<string>("LabourCost")
                        .HasMaxLength(50);

                    b.Property<int?>("LandDetailIDFK");

                    b.Property<string>("NameofthePestSide")
                        .HasMaxLength(50);

                    b.Property<int?>("PartitionLandDetailIDFK");

                    b.Property<string>("Purpose")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.HasIndex("LandDetailIDFK");

                    b.HasIndex("PartitionLandDetailIDFK");

                    b.ToTable("PestControls");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.Plowing", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("DateModified");

                    b.Property<bool>("Deleted")
                        .HasMaxLength(50);

                    b.Property<int?>("LandDetailIDFK");

                    b.Property<int?>("PartitionLandDetailIDFK");

                    b.Property<DateTime>("PlowingDate");

                    b.Property<string>("PlowingExp")
                        .HasMaxLength(50);

                    b.Property<string>("TypeofPlowing")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.HasIndex("LandDetailIDFK");

                    b.HasIndex("PartitionLandDetailIDFK");

                    b.ToTable("Plowings");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.Registration", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("DateModified");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Email");

                    b.Property<string>("MobileNumber");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.RolePageAccess", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("DateModified");

                    b.Property<bool>("Deleted");

                    b.Property<int>("PagesID");

                    b.Property<int>("RolesID");

                    b.HasKey("ID");

                    b.HasIndex("PagesID");

                    b.HasIndex("RolesID");

                    b.ToTable("RolePageAccesses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DateAdded = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(4061),
                            DateModified = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(4062),
                            Deleted = false,
                            PagesID = 1,
                            RolesID = 1
                        },
                        new
                        {
                            ID = 2,
                            DateAdded = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5349),
                            DateModified = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5350),
                            Deleted = false,
                            PagesID = 2,
                            RolesID = 1
                        },
                        new
                        {
                            ID = 3,
                            DateAdded = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5361),
                            DateModified = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5361),
                            Deleted = false,
                            PagesID = 3,
                            RolesID = 1
                        },
                        new
                        {
                            ID = 4,
                            DateAdded = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5362),
                            DateModified = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5363),
                            Deleted = false,
                            PagesID = 4,
                            RolesID = 1
                        },
                        new
                        {
                            ID = 5,
                            DateAdded = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5364),
                            DateModified = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5364),
                            Deleted = false,
                            PagesID = 5,
                            RolesID = 1
                        },
                        new
                        {
                            ID = 6,
                            DateAdded = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5366),
                            DateModified = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5366),
                            Deleted = false,
                            PagesID = 6,
                            RolesID = 1
                        },
                        new
                        {
                            ID = 7,
                            DateAdded = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5442),
                            DateModified = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5442),
                            Deleted = false,
                            PagesID = 7,
                            RolesID = 1
                        },
                        new
                        {
                            ID = 8,
                            DateAdded = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5444),
                            DateModified = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5444),
                            Deleted = false,
                            PagesID = 8,
                            RolesID = 1
                        },
                        new
                        {
                            ID = 9,
                            DateAdded = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5445),
                            DateModified = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5446),
                            Deleted = false,
                            PagesID = 9,
                            RolesID = 1
                        },
                        new
                        {
                            ID = 10,
                            DateAdded = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5447),
                            DateModified = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5447),
                            Deleted = false,
                            PagesID = 10,
                            RolesID = 1
                        },
                        new
                        {
                            ID = 11,
                            DateAdded = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5448),
                            DateModified = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5448),
                            Deleted = false,
                            PagesID = 1,
                            RolesID = 2
                        },
                        new
                        {
                            ID = 12,
                            DateAdded = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5450),
                            DateModified = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5450),
                            Deleted = false,
                            PagesID = 2,
                            RolesID = 2
                        },
                        new
                        {
                            ID = 13,
                            DateAdded = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5451),
                            DateModified = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5451),
                            Deleted = false,
                            PagesID = 3,
                            RolesID = 2
                        },
                        new
                        {
                            ID = 14,
                            DateAdded = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5452),
                            DateModified = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5453),
                            Deleted = false,
                            PagesID = 4,
                            RolesID = 2
                        },
                        new
                        {
                            ID = 15,
                            DateAdded = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5454),
                            DateModified = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5455),
                            Deleted = false,
                            PagesID = 5,
                            RolesID = 2
                        },
                        new
                        {
                            ID = 16,
                            DateAdded = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5456),
                            DateModified = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5456),
                            Deleted = false,
                            PagesID = 6,
                            RolesID = 2
                        },
                        new
                        {
                            ID = 17,
                            DateAdded = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5457),
                            DateModified = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5457),
                            Deleted = false,
                            PagesID = 7,
                            RolesID = 2
                        },
                        new
                        {
                            ID = 18,
                            DateAdded = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5458),
                            DateModified = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5459),
                            Deleted = false,
                            PagesID = 8,
                            RolesID = 2
                        },
                        new
                        {
                            ID = 19,
                            DateAdded = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5460),
                            DateModified = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5460),
                            Deleted = false,
                            PagesID = 9,
                            RolesID = 2
                        },
                        new
                        {
                            ID = 20,
                            DateAdded = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5461),
                            DateModified = new DateTime(2020, 3, 12, 3, 28, 10, 370, DateTimeKind.Utc).AddTicks(5462),
                            Deleted = false,
                            PagesID = 10,
                            RolesID = 2
                        });
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.Roles", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted");

                    b.Property<string>("Name");

                    b.Property<string>("Text");

                    b.HasKey("ID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Deleted = false,
                            Name = "Admin",
                            Text = "Admin"
                        },
                        new
                        {
                            ID = 2,
                            Deleted = false,
                            Name = "User",
                            Text = "User"
                        },
                        new
                        {
                            ID = 3,
                            Deleted = false,
                            Name = "SiteAdmin",
                            Text = "Admin"
                        });
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.Sale", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BuyerMobileNumber")
                        .HasMaxLength(50);

                    b.Property<string>("BuyerName")
                        .HasMaxLength(50);

                    b.Property<string>("Date");

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("DateModified");

                    b.Property<bool>("Deleted");

                    b.Property<int?>("LandDetailIDFK");

                    b.Property<int?>("PartitionLandDetailIDFK");

                    b.Property<string>("Price")
                        .HasMaxLength(50);

                    b.Property<string>("Quantity")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.HasIndex("LandDetailIDFK");

                    b.HasIndex("PartitionLandDetailIDFK");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.Seeding", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("DateModified");

                    b.Property<bool>("Deleted");

                    b.Property<int>("LabourCost");

                    b.Property<int?>("LandDetailIDFK");

                    b.Property<string>("NOofLabours")
                        .HasMaxLength(50);

                    b.Property<int?>("PartitionLandDetailIDFK");

                    b.Property<string>("Quantity")
                        .HasMaxLength(50);

                    b.Property<string>("SeedCost")
                        .HasMaxLength(50);

                    b.Property<string>("SeedName")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.HasIndex("LandDetailIDFK");

                    b.HasIndex("PartitionLandDetailIDFK");

                    b.ToTable("Seedings");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.StateList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StateName");

                    b.HasKey("ID");

                    b.ToTable("StateLists");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AcceptedTermsAndConditions");

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("DateModified");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .HasMaxLength(30);

                    b.Property<bool>("IsFirstTimeLogin");

                    b.Property<string>("LastName")
                        .HasMaxLength(30);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("ResetPasswordToken");

                    b.Property<int>("RoleID");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AcceptedTermsAndConditions = true,
                            DateAdded = new DateTime(2020, 3, 12, 3, 28, 10, 367, DateTimeKind.Utc).AddTicks(7072),
                            DateModified = new DateTime(2020, 3, 12, 3, 28, 10, 367, DateTimeKind.Utc).AddTicks(7097),
                            Deleted = false,
                            Email = "winedjos@gmail.com",
                            IsFirstTimeLogin = true,
                            Password = "llFg1YwNHgLVbQGDz1aaEQ==",
                            RoleID = 1,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.UserActivity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<DateTime>("TimeStamp");

                    b.Property<int>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("UserActivity");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.WebPages", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted");

                    b.Property<string>("Name");

                    b.Property<string>("Text");

                    b.Property<string>("Url");

                    b.HasKey("ID");

                    b.ToTable("WebPages");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Deleted = false,
                            Name = "ManageLand",
                            Text = "Land",
                            Url = "/manageland"
                        },
                        new
                        {
                            ID = 2,
                            Deleted = false,
                            Name = "ManagePartition",
                            Text = "Partition",
                            Url = "/managepartition"
                        },
                        new
                        {
                            ID = 3,
                            Deleted = false,
                            Name = "Plowing",
                            Text = "Plowing ",
                            Url = "/plowing "
                        },
                        new
                        {
                            ID = 4,
                            Deleted = false,
                            Name = "Seeding",
                            Text = "Seeding",
                            Url = "/seeding"
                        },
                        new
                        {
                            ID = 5,
                            Deleted = false,
                            Name = "PestControl",
                            Text = "Pest Control",
                            Url = "/pestcontrol"
                        },
                        new
                        {
                            ID = 6,
                            Deleted = false,
                            Name = "WeedRemove",
                            Text = "Weed Remove",
                            Url = "/weedremove"
                        },
                        new
                        {
                            ID = 7,
                            Deleted = false,
                            Name = "PostLogin",
                            Text = "Post Login",
                            Url = "/postlogin"
                        },
                        new
                        {
                            ID = 8,
                            Deleted = false,
                            Name = "Harvesting",
                            Text = "Harvesting",
                            Url = "/harvesting"
                        },
                        new
                        {
                            ID = 9,
                            Deleted = false,
                            Name = "Sale",
                            Text = "Sale",
                            Url = "/sale"
                        },
                        new
                        {
                            ID = 10,
                            Deleted = false,
                            Name = "Report",
                            Text = "Report",
                            Url = "/report"
                        });
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.WeedRemove", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cost")
                        .HasMaxLength(50);

                    b.Property<string>("Date");

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("DateModified");

                    b.Property<bool>("Deleted");

                    b.Property<int>("LabourCost");

                    b.Property<int?>("LandDetailIDFK");

                    b.Property<string>("NOofLabours")
                        .HasMaxLength(50);

                    b.Property<int?>("PartitionLandDetailIDFK");

                    b.HasKey("ID");

                    b.HasIndex("LandDetailIDFK");

                    b.HasIndex("PartitionLandDetailIDFK");

                    b.ToTable("WeedRemove");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.Harvestings", b =>
                {
                    b.HasOne("ThaniyasFarmerAppAPI.Models.LandDetail", "LandDetailsId")
                        .WithMany()
                        .HasForeignKey("LandDetailIDFK");

                    b.HasOne("ThaniyasFarmerAppAPI.Models.PartitionLandDetail", "PartitionLandDetailId")
                        .WithMany()
                        .HasForeignKey("PartitionLandDetailIDFK");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.LandDetail", b =>
                {
                    b.HasOne("ThaniyasFarmerAppAPI.Models.StateList", "State")
                        .WithMany()
                        .HasForeignKey("StateListId");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.PartitionLandDetail", b =>
                {
                    b.HasOne("ThaniyasFarmerAppAPI.Models.LandDetail", "LandDetail")
                        .WithMany("PartitionLandDetails")
                        .HasForeignKey("LandDetailId");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.PestControl", b =>
                {
                    b.HasOne("ThaniyasFarmerAppAPI.Models.LandDetail", "LandDetailsId")
                        .WithMany()
                        .HasForeignKey("LandDetailIDFK");

                    b.HasOne("ThaniyasFarmerAppAPI.Models.PartitionLandDetail", "PartitionLandDetailId")
                        .WithMany()
                        .HasForeignKey("PartitionLandDetailIDFK");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.Plowing", b =>
                {
                    b.HasOne("ThaniyasFarmerAppAPI.Models.LandDetail", "LandDetailsId")
                        .WithMany()
                        .HasForeignKey("LandDetailIDFK");

                    b.HasOne("ThaniyasFarmerAppAPI.Models.PartitionLandDetail", "PartitionLandDetailId")
                        .WithMany()
                        .HasForeignKey("PartitionLandDetailIDFK");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.RolePageAccess", b =>
                {
                    b.HasOne("ThaniyasFarmerAppAPI.Models.WebPages", "Pages")
                        .WithMany()
                        .HasForeignKey("PagesID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ThaniyasFarmerAppAPI.Models.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("RolesID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.Sale", b =>
                {
                    b.HasOne("ThaniyasFarmerAppAPI.Models.LandDetail", "LandDetailsId")
                        .WithMany()
                        .HasForeignKey("LandDetailIDFK");

                    b.HasOne("ThaniyasFarmerAppAPI.Models.PartitionLandDetail", "PartitionLandDetailId")
                        .WithMany()
                        .HasForeignKey("PartitionLandDetailIDFK");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.Seeding", b =>
                {
                    b.HasOne("ThaniyasFarmerAppAPI.Models.LandDetail", "LandDetailsId")
                        .WithMany()
                        .HasForeignKey("LandDetailIDFK");

                    b.HasOne("ThaniyasFarmerAppAPI.Models.PartitionLandDetail", "PartitionLandDetailId")
                        .WithMany()
                        .HasForeignKey("PartitionLandDetailIDFK");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.UserActivity", b =>
                {
                    b.HasOne("ThaniyasFarmerAppAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.WeedRemove", b =>
                {
                    b.HasOne("ThaniyasFarmerAppAPI.Models.LandDetail", "LandDetailsId")
                        .WithMany()
                        .HasForeignKey("LandDetailIDFK");

                    b.HasOne("ThaniyasFarmerAppAPI.Models.PartitionLandDetail", "PartitionLandDetailId")
                        .WithMany()
                        .HasForeignKey("PartitionLandDetailIDFK");
                });
#pragma warning restore 612, 618
        }
    }
}
