// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThaniyasFarmerAppAPI.Repository;

namespace ThaniyasFarmerAppAPI.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20200810061159_PartLand_notes")]
    partial class PartLand_notes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.Configuration", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("DateModified");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Name");

                    b.Property<int?>("ParentID");

                    b.Property<string>("Text");

                    b.Property<string>("Type");

                    b.Property<string>("Value");

                    b.HasKey("ID");

                    b.ToTable("Configurations");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 872, DateTimeKind.Utc).AddTicks(6338),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 872, DateTimeKind.Utc).AddTicks(6339),
                            Deleted = false,
                            Name = "UserID",
                            Type = "SystemEmailSettings",
                            Value = "vNp/Rg/59Wq/aUZBS0+1LDWmAArWOdzzJByWFcSqj9c="
                        },
                        new
                        {
                            ID = 2,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 872, DateTimeKind.Utc).AddTicks(8413),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 872, DateTimeKind.Utc).AddTicks(8413),
                            Deleted = false,
                            Name = "Password",
                            Type = "SystemEmailSettings",
                            Value = "DR7VkCQllyJBLRHqnhoFLg=="
                        },
                        new
                        {
                            ID = 3,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 872, DateTimeKind.Utc).AddTicks(9084),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 872, DateTimeKind.Utc).AddTicks(9085),
                            Deleted = false,
                            Name = "SMTPPort",
                            Type = "SystemEmailSettings",
                            Value = "KfPgC+VOAFLCwNmgAKPmfQ=="
                        },
                        new
                        {
                            ID = 4,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 872, DateTimeKind.Utc).AddTicks(9664),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 872, DateTimeKind.Utc).AddTicks(9664),
                            Deleted = false,
                            Name = "Host",
                            Type = "SystemEmailSettings",
                            Value = "+fNJD/SKxu6Pyz64X9mIMQ=="
                        });
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.GoogleRegister", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("DateModified");

                    b.Property<bool>("Deleted");

                    b.Property<int>("UserId");

                    b.Property<string>("accessToken");

                    b.Property<string>("email");

                    b.Property<string>("familyName");

                    b.Property<string>("givenName");

                    b.Property<string>("googleid");

                    b.Property<string>("idToken");

                    b.Property<string>("imageUrl");

                    b.Property<string>("name");

                    b.Property<string>("serverAuthCode");

                    b.HasKey("ID");

                    b.HasIndex("UserId");

                    b.ToTable("GoogleRegisters");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.Harvestings", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cost")
                        .HasMaxLength(50);

                    b.Property<DateTime>("Date");

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("DateModified");

                    b.Property<bool>("Deleted");

                    b.Property<int>("LabourCost");

                    b.Property<string>("NoOfLabours")
                        .HasMaxLength(50);

                    b.Property<int>("PartitionLandDetailId");

                    b.Property<int>("UserId");

                    b.HasKey("ID");

                    b.HasIndex("PartitionLandDetailId");

                    b.HasIndex("UserId");

                    b.ToTable("Harvestings");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.LandDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AreaSize");

                    b.Property<string>("City")
                        .HasMaxLength(50);

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("DateModified");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75);

                    b.Property<string>("Notes")
                        .HasMaxLength(50);

                    b.Property<string>("PattaNumber")
                        .HasMaxLength(50);

                    b.Property<int>("StateId");

                    b.Property<string>("SurveyNumber")
                        .HasMaxLength(50);

                    b.Property<int>("UserId");

                    b.Property<string>("Village")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.HasIndex("StateId");

                    b.HasIndex("UserId");

                    b.ToTable("LandDetails");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.PartitionLandDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AreaSize")
                        .IsRequired()
                        .HasMaxLength(75);

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("DateModified");

                    b.Property<bool>("Deleted")
                        .HasMaxLength(50);

                    b.Property<int>("LandDetailId");

                    b.Property<string>("LandDirection")
                        .IsRequired()
                        .HasMaxLength(75);

                    b.Property<string>("Notes");

                    b.Property<int>("UserId");

                    b.HasKey("ID");

                    b.HasIndex("LandDetailId");

                    b.HasIndex("UserId");

                    b.ToTable("PartitionLandDetails");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.PestControl", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cost")
                        .HasMaxLength(50);

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("DateModified");

                    b.Property<bool>("Deleted")
                        .HasMaxLength(50);

                    b.Property<string>("LabourCost")
                        .HasMaxLength(50);

                    b.Property<string>("NameofthePestSide")
                        .HasMaxLength(50);

                    b.Property<int>("PartitionLandDetailId");

                    b.Property<DateTime>("PestControlDate");

                    b.Property<string>("Purpose")
                        .HasMaxLength(50);

                    b.Property<int>("UserId");

                    b.HasKey("ID");

                    b.HasIndex("PartitionLandDetailId");

                    b.HasIndex("UserId");

                    b.ToTable("PestControls");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.Plowing", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("DateModified");

                    b.Property<bool>("Deleted")
                        .HasMaxLength(50);

                    b.Property<int>("PartitionLandDetailId");

                    b.Property<DateTime>("PlowingDate");

                    b.Property<string>("PlowingExp")
                        .HasMaxLength(50);

                    b.Property<string>("TypeofPlowing")
                        .HasMaxLength(50);

                    b.Property<int>("UserId");

                    b.HasKey("ID");

                    b.HasIndex("PartitionLandDetailId");

                    b.HasIndex("UserId");

                    b.ToTable("Plowings");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.RolePageAccess", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("DateModified");

                    b.Property<bool>("Deleted");

                    b.Property<int>("PagesID");

                    b.Property<int>("RolesID");

                    b.HasKey("ID");

                    b.HasIndex("PagesID");

                    b.HasIndex("RolesID");

                    b.ToTable("RolePageAccesses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(8346),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(8347),
                            Deleted = false,
                            PagesID = 1,
                            RolesID = 1
                        },
                        new
                        {
                            ID = 2,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9173),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9174),
                            Deleted = false,
                            PagesID = 2,
                            RolesID = 1
                        },
                        new
                        {
                            ID = 3,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9180),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9180),
                            Deleted = false,
                            PagesID = 3,
                            RolesID = 1
                        },
                        new
                        {
                            ID = 4,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9181),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9181),
                            Deleted = false,
                            PagesID = 4,
                            RolesID = 1
                        },
                        new
                        {
                            ID = 5,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9181),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9182),
                            Deleted = false,
                            PagesID = 5,
                            RolesID = 1
                        },
                        new
                        {
                            ID = 6,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9182),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9182),
                            Deleted = false,
                            PagesID = 6,
                            RolesID = 1
                        },
                        new
                        {
                            ID = 7,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9183),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9183),
                            Deleted = false,
                            PagesID = 7,
                            RolesID = 1
                        },
                        new
                        {
                            ID = 8,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9184),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9184),
                            Deleted = false,
                            PagesID = 8,
                            RolesID = 1
                        },
                        new
                        {
                            ID = 9,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9184),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9185),
                            Deleted = false,
                            PagesID = 9,
                            RolesID = 1
                        },
                        new
                        {
                            ID = 10,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9185),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9185),
                            Deleted = false,
                            PagesID = 10,
                            RolesID = 1
                        },
                        new
                        {
                            ID = 11,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9186),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9186),
                            Deleted = false,
                            PagesID = 1,
                            RolesID = 2
                        },
                        new
                        {
                            ID = 12,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9187),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9187),
                            Deleted = false,
                            PagesID = 2,
                            RolesID = 2
                        },
                        new
                        {
                            ID = 13,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9187),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9188),
                            Deleted = false,
                            PagesID = 3,
                            RolesID = 2
                        },
                        new
                        {
                            ID = 14,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9188),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9189),
                            Deleted = false,
                            PagesID = 4,
                            RolesID = 2
                        },
                        new
                        {
                            ID = 15,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9190),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9190),
                            Deleted = false,
                            PagesID = 5,
                            RolesID = 2
                        },
                        new
                        {
                            ID = 16,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9190),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9191),
                            Deleted = false,
                            PagesID = 6,
                            RolesID = 2
                        },
                        new
                        {
                            ID = 17,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9191),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9191),
                            Deleted = false,
                            PagesID = 7,
                            RolesID = 2
                        },
                        new
                        {
                            ID = 18,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9192),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9192),
                            Deleted = false,
                            PagesID = 8,
                            RolesID = 2
                        },
                        new
                        {
                            ID = 19,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9193),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9193),
                            Deleted = false,
                            PagesID = 9,
                            RolesID = 2
                        },
                        new
                        {
                            ID = 20,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9193),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 873, DateTimeKind.Utc).AddTicks(9194),
                            Deleted = false,
                            PagesID = 10,
                            RolesID = 2
                        });
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.Roles", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted");

                    b.Property<string>("Name");

                    b.Property<string>("Text");

                    b.HasKey("ID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Deleted = false,
                            Name = "Admin",
                            Text = "Admin"
                        },
                        new
                        {
                            ID = 2,
                            Deleted = false,
                            Name = "User",
                            Text = "User"
                        },
                        new
                        {
                            ID = 3,
                            Deleted = false,
                            Name = "SiteAdmin",
                            Text = "Admin"
                        });
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.Sale", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BuyerMobileNumber")
                        .HasMaxLength(50);

                    b.Property<string>("BuyerName")
                        .HasMaxLength(50);

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("DateModified");

                    b.Property<bool>("Deleted");

                    b.Property<int>("PartitionLandDetailId");

                    b.Property<string>("Price")
                        .HasMaxLength(50);

                    b.Property<string>("Quantity")
                        .HasMaxLength(50);

                    b.Property<DateTime>("SaleDate");

                    b.Property<int>("UserId");

                    b.HasKey("ID");

                    b.HasIndex("PartitionLandDetailId");

                    b.HasIndex("UserId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.Seeding", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasMaxLength(50);

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("DateModified");

                    b.Property<bool>("Deleted");

                    b.Property<int>("LabourCost");

                    b.Property<string>("NoOfLabours")
                        .HasMaxLength(50);

                    b.Property<int>("PartitionLandDetailId");

                    b.Property<string>("Quantity")
                        .HasMaxLength(50);

                    b.Property<string>("SeedCost");

                    b.Property<string>("SeedName")
                        .HasMaxLength(50);

                    b.Property<int>("UserId");

                    b.HasKey("ID");

                    b.HasIndex("PartitionLandDetailId");

                    b.HasIndex("UserId");

                    b.ToTable("Seedings");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.StateList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StateName");

                    b.HasKey("ID");

                    b.ToTable("StateLists");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            StateName = "Tamilnadu"
                        },
                        new
                        {
                            ID = 2,
                            StateName = "Kerala"
                        },
                        new
                        {
                            ID = 3,
                            StateName = "Karnataka"
                        });
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AcceptedTermsAndConditions");

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("DateModified");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .HasMaxLength(30);

                    b.Property<bool>("IsFirstTimeLogin");

                    b.Property<string>("LastName")
                        .HasMaxLength(30);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("ResetPasswordToken");

                    b.Property<int>("RoleID");

                    b.Property<string>("Source");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AcceptedTermsAndConditions = false,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 872, DateTimeKind.Utc).AddTicks(653),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 872, DateTimeKind.Utc).AddTicks(663),
                            Deleted = false,
                            Email = "winedjos@gmail.com",
                            IsFirstTimeLogin = true,
                            Password = "llFg1YwNHgLVbQGDz1aaEQ==",
                            RoleID = 0,
                            UserName = "admin"
                        },
                        new
                        {
                            ID = 2,
                            AcceptedTermsAndConditions = true,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 872, DateTimeKind.Utc).AddTicks(1783),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 872, DateTimeKind.Utc).AddTicks(1784),
                            Deleted = false,
                            Email = "seenu@inisys.in",
                            IsFirstTimeLogin = true,
                            Password = "llFg1YwNHgLVbQGDz1aaEQ==",
                            RoleID = 1,
                            UserName = "seenu"
                        },
                        new
                        {
                            ID = 3,
                            AcceptedTermsAndConditions = true,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 872, DateTimeKind.Utc).AddTicks(2982),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 872, DateTimeKind.Utc).AddTicks(2983),
                            Deleted = false,
                            Email = "senthil@gmail.com",
                            IsFirstTimeLogin = true,
                            Password = "llFg1YwNHgLVbQGDz1aaEQ==",
                            RoleID = 1,
                            UserName = "senthil"
                        },
                        new
                        {
                            ID = 4,
                            AcceptedTermsAndConditions = true,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 872, DateTimeKind.Utc).AddTicks(3610),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 872, DateTimeKind.Utc).AddTicks(3611),
                            Deleted = false,
                            Email = "seetha@inisys.in",
                            IsFirstTimeLogin = true,
                            Password = "llFg1YwNHgLVbQGDz1aaEQ==",
                            RoleID = 1,
                            UserName = "seetha"
                        },
                        new
                        {
                            ID = 5,
                            AcceptedTermsAndConditions = true,
                            DateAdded = new DateTime(2020, 8, 10, 6, 11, 58, 872, DateTimeKind.Utc).AddTicks(4174),
                            DateModified = new DateTime(2020, 8, 10, 6, 11, 58, 872, DateTimeKind.Utc).AddTicks(4174),
                            Deleted = false,
                            Email = "edwin@inisys.in",
                            IsFirstTimeLogin = true,
                            Password = "llFg1YwNHgLVbQGDz1aaEQ==",
                            RoleID = 1,
                            UserName = "edwin"
                        });
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.UserActivity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<DateTime>("TimeStamp");

                    b.Property<int>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("UserActivity");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.WebPages", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted");

                    b.Property<string>("Name");

                    b.Property<string>("Text");

                    b.Property<string>("Url");

                    b.HasKey("ID");

                    b.ToTable("WebPages");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Deleted = false,
                            Name = "ManageLand",
                            Text = "Land",
                            Url = "/manageland"
                        },
                        new
                        {
                            ID = 2,
                            Deleted = false,
                            Name = "ManagePartition",
                            Text = "Partition",
                            Url = "/managepartition"
                        },
                        new
                        {
                            ID = 3,
                            Deleted = false,
                            Name = "Plowing",
                            Text = "Plowing ",
                            Url = "/plowing "
                        },
                        new
                        {
                            ID = 4,
                            Deleted = false,
                            Name = "Seeding",
                            Text = "Seeding",
                            Url = "/seeding"
                        },
                        new
                        {
                            ID = 5,
                            Deleted = false,
                            Name = "PestControl",
                            Text = "Pest Control",
                            Url = "/pestcontrol"
                        },
                        new
                        {
                            ID = 6,
                            Deleted = false,
                            Name = "WeedRemove",
                            Text = "Weed Remove",
                            Url = "/weedremove"
                        },
                        new
                        {
                            ID = 7,
                            Deleted = false,
                            Name = "PostLogin",
                            Text = "Post Login",
                            Url = "/postlogin"
                        },
                        new
                        {
                            ID = 8,
                            Deleted = false,
                            Name = "Harvesting",
                            Text = "Harvesting",
                            Url = "/harvesting"
                        },
                        new
                        {
                            ID = 9,
                            Deleted = false,
                            Name = "Sale",
                            Text = "Sale",
                            Url = "/sale"
                        },
                        new
                        {
                            ID = 10,
                            Deleted = false,
                            Name = "Report",
                            Text = "Report",
                            Url = "/report"
                        });
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.WeedRemove", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cost")
                        .HasMaxLength(50);

                    b.Property<DateTime>("Date");

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("DateModified");

                    b.Property<bool>("Deleted");

                    b.Property<int>("LabourCost");

                    b.Property<string>("NoOfLabours")
                        .HasMaxLength(50);

                    b.Property<int>("PartitionLandDetailId");

                    b.Property<int>("UserId");

                    b.HasKey("ID");

                    b.HasIndex("PartitionLandDetailId");

                    b.HasIndex("UserId");

                    b.ToTable("WeedRemove");
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.GoogleRegister", b =>
                {
                    b.HasOne("ThaniyasFarmerAppAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.Harvestings", b =>
                {
                    b.HasOne("ThaniyasFarmerAppAPI.Models.PartitionLandDetail", "PartitionLandDetail")
                        .WithMany("Harvestings")
                        .HasForeignKey("PartitionLandDetailId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ThaniyasFarmerAppAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.LandDetail", b =>
                {
                    b.HasOne("ThaniyasFarmerAppAPI.Models.StateList", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ThaniyasFarmerAppAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.PartitionLandDetail", b =>
                {
                    b.HasOne("ThaniyasFarmerAppAPI.Models.LandDetail", "LandDetail")
                        .WithMany("PartitionLandDetails")
                        .HasForeignKey("LandDetailId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ThaniyasFarmerAppAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.PestControl", b =>
                {
                    b.HasOne("ThaniyasFarmerAppAPI.Models.PartitionLandDetail", "PartitionLandDetail")
                        .WithMany("PestControls")
                        .HasForeignKey("PartitionLandDetailId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ThaniyasFarmerAppAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.Plowing", b =>
                {
                    b.HasOne("ThaniyasFarmerAppAPI.Models.PartitionLandDetail", "PartitionLandDetail")
                        .WithMany("Plowings")
                        .HasForeignKey("PartitionLandDetailId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ThaniyasFarmerAppAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.RolePageAccess", b =>
                {
                    b.HasOne("ThaniyasFarmerAppAPI.Models.WebPages", "Pages")
                        .WithMany()
                        .HasForeignKey("PagesID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ThaniyasFarmerAppAPI.Models.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("RolesID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.Sale", b =>
                {
                    b.HasOne("ThaniyasFarmerAppAPI.Models.PartitionLandDetail", "PartitionLandDetail")
                        .WithMany("Sales")
                        .HasForeignKey("PartitionLandDetailId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ThaniyasFarmerAppAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.Seeding", b =>
                {
                    b.HasOne("ThaniyasFarmerAppAPI.Models.PartitionLandDetail", "PartitionLandDetail")
                        .WithMany("Seedings")
                        .HasForeignKey("PartitionLandDetailId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ThaniyasFarmerAppAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.UserActivity", b =>
                {
                    b.HasOne("ThaniyasFarmerAppAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ThaniyasFarmerAppAPI.Models.WeedRemove", b =>
                {
                    b.HasOne("ThaniyasFarmerAppAPI.Models.PartitionLandDetail", "PartitionLandDetail")
                        .WithMany("WeedRemoves")
                        .HasForeignKey("PartitionLandDetailId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ThaniyasFarmerAppAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
